kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-storage-class
  labels:
    {{- include "gitlab-server.labels" . | nindent 4 }}
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  labels:
    {{- include "gitlab-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: efs-storage-class
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persistent-volume
  labels:
    {{- include "gitlab-server.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-storage-class
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs_id }}
