apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-server.fullname" . }}
  labels:
    {{- include "gitlab-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh

  selector:
    {{- include "gitlab-server.selectorLabels" . | nindent 4 }}
