kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-storage-class
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: efs-storage-class
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persistent-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-storage-class
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-5e768cdc
